{{- range .Values.inferenceObjectives }}
---
apiVersion: llm-d.ai/v1alpha2
kind: InferenceObjective
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "llm-d-router.labels" $ | nindent 4 }}
spec:
  priority: {{ .priority }}
  poolRef:
    group: {{ index (splitList "/" $.Values.router.inferencePool.apiVersion) 0 }}
    name: {{ $.Release.Name }}
{{- end }}